---

- name: Update config view file
  hosts: localhost
  gather_facts: no
  tasks:

    # This is needed. If the file exists, Ansible tries to
    # lookup the files attributes, but is stopped by Apparmor.
    - name: Remove config view file
      file:
        path: "{{ lookup('env','SNAP_DATA') }}/config-view"
        state: absent

    - name: Write config view file
      template:
        src: templates/config-view.j2
        dest: "{{ lookup('env','SNAP_DATA') }}/config-view"
        force: yes
