---

- name: Destroy containers
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Destroy containers
      lxd_container:
        name: "{{ item }}"
        state: absent
        snap_url: None # This is needed, bug!
        url: unix:/var/snap/lxd/common/lxd/unix.socket
      loop: "{{ groups['containers'] }}"
