---

- name: Update haproxy config
  hosts: localhost
  gather_facts: no
  tasks:

    - include_tasks: container-facts.yml
      when: stage == 2

    - name: Get www token from snapd
      command: snapctl get www-token
      register: token
      changed_when: no

    # This is needed. If the file exists, Ansible tries to
    # lookup the files attributes, but is stopped by Apparmor.
    - name: Remove config view file
      file:
        path: "{{ lookup('env','SNAP_DATA') }}/haproxy.cfg"
        state: absent
      changed_when: no

    - name: Update haproxy.cfg file
      template:
        src: templates/haproxy.cfg.j2
        dest: "{{ lookup('env','SNAP_DATA') }}/haproxy.cfg"
        force: yes
      changed_when: no

    - name: restart haproxy
      shell: snapctl restart mailserver.haproxy
      changed_when: no
