---

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    managers:
      hosts:
        localhost:
          ansible_connection: local
    containers:
      vars:
        ansible_connection: lxd
      hosts:
        postfix:
        dovecot:
        opendkim:
