---

name: mailserver
version: '0.1'
summary: A mailserver in a single snap
description: |
  There are a few pieces that you need to manage your own mail server.
  This snap makes the process easy, it will setup most things that
  you expect from a mail server. Because the process is automated and
  easy expect the installation to be somewhat unflexible.

base: core18
grade: devel
confinement: strict

apps:
  service:
    command: bin/service
    daemon: simple
    environment:
      LXD_DIR: /var/snap/lxd/common/lxd
      ANSIBLE_LOCAL_TEMP: /tmp
      ANSIBLE_REMOTE_TMP: /tmp
      ANSIBLE_FORCE_COLOR: "true"
    plugs:
      - network
      - lxd

  destroy:
    command: bin/snapcraft-preload ansible-playbook -i $SNAP/ansible/inventory.yml $SNAP/ansible/destroy.yml
    environment:
      LXD_DIR: /var/snap/lxd/common/lxd
      ANSIBLE_LOCAL_TEMP: /tmp
      ANSIBLE_REMOTE_TMP: /tmp
    plugs:
      - network
      - lxd

  haproxy:
    command: usr/sbin/haproxy -f $SNAP_DATA/haproxy.cfg
    daemon: simple
    plugs:
      - network
      - network-bind

  www:
    command: bin/www
    daemon: simple
    plugs:
      - network
      - network-bind

  mailserver:
    command: bin/mailservercmd
    plugs:
      - network

  provision-logs:
    command: cat $SNAP_DATA/provision.log

  trigger-provision:
    command: touch $SNAP_DATA/do-provision

parts:
  snapcraft-preload:
    # Ansible uses python multiprocessing and semaphores in /dev/shm
    # Apparmor will block these we need to redirect the calls with
    # a patched version of sergiusens snapcraft-preload:
    # https://github.com/sergiusens/snapcraft-preload/pull/29
    source: https://github.com/diddledan/snapcraft-preload.git
    source-branch: semaphore-support

    plugin: cmake
    build-packages:
      - on amd64:
        - gcc-multilib
        - g++-multilib

  shell:
    plugin: nil
    stage-packages:
      - bash

  manager:
    plugin: dump
    source: manager

  www:
    plugin: python
    source: www
    python-packages:
      # bug: https://github.com/kennethreitz/responder/issues/337
      - git+https://github.com/kennethreitz/responder

  ansible:
    plugin: python
    python-packages:
      - ansible==2.7.9
    stage-packages:
      - lxd

  haproxy:
    plugin: nil
    stage-packages:
      - haproxy
